### PR TITLE
Migration to the latest Swift 3.0 syntax and macOS Cocoa API

### PR DESCRIPTION
**Pull request by pawlowskialex**

### CODE REVIEW

**Comment by yniesp** [comment]
I'm excited! Can't wait for this to merge in!

**Comment by robertjpayne** [comment]
@pawlowskialex what commit hash did you base this PR request on? Have you merged the latest feature/0.40.0 branch in? Looks like a lot of the changes have already been done in that branch like lowercasing enums etc…

**Comment by pawlowskialex** [comment]
@robertjpayne the top of feature/0.40.0 branch, that's 8355410.
A lot of changes has been already done, but only for iOS/tvOS. I've made the same for macOS.

**Comment by robertjpayne** [comment]
@pawlowskialex thanks for this 👍

**Pull request merged**
