### PR TITLE
change the result constraint of maker.center.equalTo(CGPoint) to based on the original point of superview

### PR DESCRIPTION
**Pull request by LiVincent-Zhang**

### CODE REVIEW

**Comment by robertjpayne** [comment]
@LiVincent-Zhang I'll need to look at this further but from first glance I don't believe this will allow for the proper behavior when relating to another view explicitly e.g. `make.center.equalTo(otherView)`

If the `from` attribute is `centerX` it should *only* go to `left` if the `equalTo` is implied superview.

**Comment by LiVincent-Zhang** [comment]
@robertjpayne Yes, I realized this is not correct.

**Comment by LiVincent-Zhang** [comment]
@robertjpayne  can you review the new commit?

**Comment by robertjpayne** [comment]
@LiVincent-Zhang thanks!

**Pull request merged**
