### PR TITLE
If you want padding those should be negative

### PR DESCRIPTION
**Pull request by julien-c**

### CODE REVIEW

**Comment by robertjpayne** [comment]
@julien-c thank you!

**Comment by julien-c** [comment]
No problem! Looks like there's a glitch on the generated page though

screenshot 2015-06-11 a 13 57 14

**Comment by robertjpayne** [comment]
Oof, looks like Github Pages having some issues with Swift syntax, I'll just remove the highlights for now.

**Comment by robertjpayne** [comment]
Fixed for now…

**Pull request merged**
