### PR TITLE
Swift 4 + Xcode 9 mac compatible

### PR DESCRIPTION
**Pull request by wolffan**
This is basically taking the xcode-4 branch and applying changes so it's usable for mac users of the library

BTW it's using beta 3

### CODE REVIEW

**Comment by robertjpayne** [comment]
@wolffan do you mean xcode-4 or swift-4?

**Comment by wolffan** [comment]
@robertjpayne Xcode 9 😅

**Comment by wolffan** [comment]
I just took the open PR and added the appropriate modifications for mac

**Comment by robertjpayne** [comment]
@wolffan whats your thoughts on the try-aliases just being `LayoutRelation` or `LayoutAttributes` rather than `NSLayoutAttributesGeneric`? I'm just not settled on the `Generic` suffixes

**Comment by wolffan** [comment]
@robertjpayne you mean in terms of naming? My logic was, keep as much as possible the existing naming convention.

But if you prefer LayoutAttributes and not NSLayoutAttributesGeneric i'm all for that :D

**Comment by wolffan** [comment]
@robertjpayne renamed!

**Comment by gbasile** [comment]
Good work @wolffan! 

Any update on this getting merged?

**Comment by robertjpayne** [comment]
@wolffan sorry one last request -- can you rebase this against the `swift-4` branch? `develop` is still targeted for Swift 3.x,

If not I'll get it merged when Swift 4.0 drops in a GM release.

**Comment by wolffan** [comment]
Seems is merged? should i rebase or not?

**Comment by robertjpayne** [comment]
I reverted it because it should go into swift-4 not develop. Sorry!

**Comment by wolffan** [comment]
@robertjpayne rebasing against swift-4 says "everything up to date"

**Pull request merged**
