### PR TITLE
Update  to Swift 4.2

### PR DESCRIPTION
**Pull request by rhysforyou**
This PR updates to SnapKit to build with Swift 4.2, which involves a few key changes:

- Update the Swift version in the project's build settings
- Update to recommended project settings as suggested by Xcode 10
- Removes the `LayoutAttribute` and `LayoutRelation` attributes used for cross platform compatibility, as now all platforms use `NSLayoutConstraint.Attribute` and `NSLayoutConstraint.Relation
- Specifies an explicit Swift version in the project's Podspec
- Updates the Swift Package Manager manifest to the latest format
- Update the Travis CI build script to use Xcode 10

I have Travis running against my fork of the repo, you can see build results here: https://travis-ci.org/rhysforyou/SnapKit

### CODE REVIEW

**Comment by spadafiva** [comment]
@rhysforyou I would love to see this added!  Thanks for doing this.

**Comment by freak4pc** [comment]
Looking into the `develop` branch (and also just built for myself on my project) - this was already resolved in #543. Seems like this PR is not needed, let me know if you think otherwise?

**Comment by aapierce0** [comment]
Sorry, I'm confused. It looks like issue #543 wasn't resolved?

In any case, I'm trying to use Swift 4.2 in my project, and as of now, adding SnapKit as a CocoaPods dependency causes my app to not compile. Using https://github.com/rhysforyou/SnapKit/tree/swift-4.2 as a remote dependency resolves it.

**Comment by freak4pc** [comment]
Sorry, I meant #516, and I meant the `develop` branch. 
Can you try adding:

```rb
pod 'SnapKit', git: 'https://github.com/SnapKit/SnapKit', branch: 'develop'
```

**Comment by aapierce0** [comment]
@freak4pc Aha, that seems to work. Thanks!

**Comment by Kalvin126** [comment]
Could we set the `spec.swift_version = '4.2'` in the `SnapKit.podspec` as well?

**Comment by freak4pc** [comment]
I don't see why you'd want to do that. It'd break backward compatibility for Swift 4 projects.
Better to leave as is, in which case it would be based on the Project's version.

**Comment by Kalvin126** [comment]
I mean I'd wish the current podspec had `spec.swift_version = '4.0', because my project is using Swift 4.2, but SnapKit and other pods are not yet 4.2 ready and CocoaPods is resolving to use my project's Swift version which is 4.2.

**Comment by Panajev** [comment]
You can run a post pod install hook adding it in your Podfile and in there force maybe even all your pod to go in Swift 4/4.1 mode... you can do more advanced processing but debugging these kind of changes is a bit of trial and error using the Xcodeproj gem Cocoapods relies on.

**Comment by Kalvin126** [comment]
oh, `spec.swift_version = '4.2'` was actually added in this PR

**Comment by codeguesser** [comment]
image
There must be some problem in it

**Comment by freak4pc** [comment]
@fassko I'm not sure what you mean exactly. I never saw a good reason to use `spec.swift_version` in the podspec level as I feel its a bit aggressive. If the project can be built on both Swift 4 and Swift 4.2, the absence of that is better so the decision is made by the project itself.

**Comment by fassko** [comment]
@freak4pc I think you're right, makes total sense. Thanks!

**Comment by freak4pc** [comment]
4.0.1 was released : https://github.com/SnapKit/SnapKit/releases/tag/4.0.1
I would close this PR If I were you, as it seems Xcode 10 backward-compatible support has been addressed.

**Comment by mattbarker016** [comment]
There's still a warning that SnapKit 4.0.1 needs to be converted to Swift 4.2

**Comment by mattbarker016** [comment]
Why was this closed? There's still a warning that SnapKit 4.0.1 needs to be converted to Swift 4.2.

**Comment by likeSo** [comment]
image

**Comment by likeSo** [comment]
You mean NSLayoutConstraint.Relation can not be used on Swift 4.2?😀 But i can see that in Xcode:
image
SnapKit version in my Podfile is 4.0.1, and my project still needs to migrate:
image
After conversion, that two changes made...

**Comment by freak4pc** [comment]
Made a PR to fix the minor warning bothering y'all :) #547

**Pull request closed without merging**
