### PR TITLE
🎉 Swift 4 Support 🎉

### PR DESCRIPTION
**Pull request by robertjpayne**
This PR is a placeholder that will be merged when Swift 4.0 becomes a public stable release. It contains all the fixes necessary to use SnapKit with the latest betas of Xcode 9 targeting Swift 4.0!

### CODE REVIEW

**Comment by Ronaldoh1** [comment]
I apologize if this is not the right place for asking questions about Swift 4.0. 

Have you guys been able to get your projects to run using the latest Xcode beta. It keep getting Module (import SnapKit) compiled with Swift 3.1 cannot be imported in Swift 3.2. I am using Xcode 9.0 beta 3. I am using snapkit branch for swift 4.  Any pointers would be greatly appreciated. cc: @pbyorke

**Comment by Ronaldoh1** [comment]
everything is working fine now 👍

**Comment by einsteinx2** [comment]
Looks like this can only compile for iOS not macOS due to UIKit references, specifically UILayoutPriority. Also there other build errors due to NSLayoutAttribute being renamed to NSLayoutConstraint.Attribute and NSLayoutRelation being renamed to NSLayoutConstraint.Relation. My coworker is fixing it in a fork now and will submit a pull request.

**Comment by wolffan** [comment]
That's the branch @einsteinx2 was refering to: https://github.com/SnapKit/SnapKit/pull/434

**Comment by rslim087g** [comment]
How do we install the swift 4 compatible version? version 3.2.0 isn't working

**Comment by wolffan** [comment]
@rslim087g make sure you point your cocoapods or carthage repo to a swift 4 branch

**Comment by codingrhythm** [comment]
I am having build error using swift-4 branch. Already using the Xcode 9 via Xcode-select. In log, heaps of errors like `error: 'EdgeInsets' has been renamed to 'NSEdgeInsets'`

**Comment by wolffan** [comment]
@codingrhythm the problems are related to mac project ?

**Comment by codingrhythm** [comment]
iOS @wolffan

**Comment by Ronaldoh1** [comment]
@codingrhythm weird ... I'm using the latest Xcode beta and everything is working fine. I'm using Carthage. 

did you do the following 

 sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer

**Comment by codingrhythm** [comment]
@ronaldoh1 of course. Updated Carthage as well.

**Comment by codingrhythm** [comment]
@Ronaldoh1 my bad, after use --Platform iOS for Carthage, it worked. Thanks.

**Comment by keith** [comment]
Now that the GM has dropped, will this be merged anytime soon?

**Pull request merged**
