### PR TITLE
Added Example-iOS.xcdodeproj and fixed examples

### PR DESCRIPTION
**Pull request by teameh**
It seemed the sample project .xcodeproj file was missing.

- Re added a new example project file
- Fixed 2 things that prevent a successful compile
- Fixed warnings in assets

See diff.

Thanks for the great project, this was the least I could do. 🙌

### CODE REVIEW

**Comment by henley7223** [comment]
please msg me in henley7223@gmail.com

**Comment by robertjpayne** [comment]
Thanks :)

**Comment by henley7223** [comment]
Sir can you help me with the snapkit apps which can access gallery and file
manager to select pictures and videos and then we can share them in
Snapchat via live snap ...

**Comment by teameh** [comment]
Lol snapkit snapchat 😆

**Comment by henley7223** [comment]
Why it's funny to you?

**Comment by teameh** [comment]
@robertjpayne are you going to tell them? 😃

**Comment by henley7223** [comment]
No I am not ...I just want the access so I can use it...

**Comment by teameh** [comment]
@henley7223 this project named Snap**Kit** has nothing to do with Snap**Chat** 🙂

**Comment by henley7223** [comment]
Ok .. do you know anything like this which one can have access with phone
gallery and then access Snapchat?

**Comment by teameh** [comment]
We don't know anything about SnapChat.

**Pull request merged**
