### PR TITLE
Update Swift Language version to 4.2 under build settings

### PR DESCRIPTION
**Pull request by ibrahimkteish**
- Update Swift Language version to 4.2 under build settings.
- Update SnapKit podspec swift version.

### CODE REVIEW

**Comment by fassko** [comment]
I think need to also bump version in podspec and maybe mention in Readme that this version is Swift 4.2

**Comment by Damonvvong** [comment]
@ibrahimkteish Trouble to update, please~

**Comment by Kaspik** [comment]
Releeeease it please! 🚀  :)

**Comment by Kaspik** [comment]
@robertjpayne Pretty please, one more PR about this warning so we can have 0 warnings projects again :)

**Comment by shoaibnomani** [comment]
Any update on this?

**Pull request merged**
