### PR TITLE
Add Swift Package Manager support

### LINKED ISSUE #399: Request: Make SnapKit compatible with Swift Package Manager
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 10.2
 SnapKit Version         | 3.1.2
 Integration Method      | _Swift Package Manager_
 

### Issue Description

Some developers now want to move past Cocoapods and Carthage as the Swift Package Manager becomes a bigger player in dependency management.

SnapKit features a Package.swift file, but its file structure is incompatible with the Swift Package Manager. After adding the GitHub .git URL as a dependency to my Package.swift file, and running `swift build`, I receive the following error:

```
Cloning https://github.com/SnapKit/SnapKit.git
HEAD is now at ad35ec4 Prepare release
Resolved version: 3.1.2
error: the package has an unsupported layout, unexpected source file(s) found: ~/Repos/Calculator/Packages/SnapKit-3.1.2/Tests/Tests.swift
fix: move the file(s) inside a module
```

As I understand, making SnapKit compatible with SPM would require only superficial changes to the source to make it meet these file structure requirements — with no significant refactoring.

It would make my workflow that much simpler if I could add a line to my Package.swift and run `swift build` rather than relying on a third party package manager or manual installation.

### PR DESCRIPTION
**Pull request by LinusU**
This adds support for SnapKit to be installed by the Swift Package Manager.

Fixes #399

### CODE REVIEW

**Comment by LinusU** [comment]
friendly ping @robertjpayne ☺️

**Comment by LinusU** [comment]
friendly ping @robertjpayne ☺️ I'd be happy to help out if you need more maintainers 👍

**Comment by SD10** [comment]
Yeah, if @robertjpayne needs help with maintenance I'm invested in SnapKit

**Comment by robertjpayne** [comment]
Hey all! Just been super busy with work 👍 This looks great thanks!

**Pull request merged**
