### PR TITLE
switched deployment target to iOS 8.0 for target and tests

### PR DESCRIPTION
**Pull request by jurvis**
Setting the deployment target as 7.0 prevents the app from being able to be submitted to the App Store with the following errors: 

```
ERROR ITMS-90362: "Invalid Info.plist value. The value for key 'MinimumOSVersion' in bundle ... is invalid. The minimum value is 8.0
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at ... does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.
ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.
```

Issue raised: https://github.com/SnapKit/SnapKit/issues/87
Thanks for the awesome work!

### CODE REVIEW

**Comment by robertjpayne** [comment]
@jurvis just out of curiosity, how are you integrating the framework with your app?

**Comment by jurvis** [comment]
@robertjpayne current using Carthage to do that

**Comment by robertjpayne** [comment]
@jurvis awesome and how are you embedding it into your target? Are you just adding them to the embedded frameworks or are you using the carthage copy-frameworks command?

Only reason I'm trying to narrow this down is because this would essentially kill using Carthage for enterprise apps that can use frameworks on iOS 7.0 just fine.

**Comment by jurvis** [comment]
@robertjpayne cool, good thinking. Didn't think about that bit on enterprise apps.

I'm currently using the carthage copy-frameworks command and adding the .framework to Linked Frameworks and Libraries (just as what Carthage instructs in the README)

**Comment by robertjpayne** [comment]
@jurvis ok, well with that in mind I'll agree and bump this as I'd rather support the majority of users rather than the enterprise minority.

**Pull request merged**
