### PR TITLE
Fix crash

### PR DESCRIPTION
**Pull request by alexanderjarvis**
This was causing an EXC Bad access crash.

### CODE REVIEW

**Comment by robertjpayne** [comment]
@alexanderjarvis do you know if this was specific to Swift-2.0 or Swift 1.x?

**Comment by alexanderjarvis** [comment]
Swift 1.2 (when a constraint was broken I think)

**Comment by robertjpayne** [comment]
@alexanderjarvis awesome, looks good but please re-submit it against develop rather than master branch. Else I can manually commit it in?

**Comment by alexanderjarvis** [comment]
@robertjpayne see #122

**Comment by alexanderjarvis** [comment]
If you change the default branch to develop this will help with future PRs

**Comment by robertjpayne** [comment]
@alexanderjarvis good point, I'll do that too and thanks for re-submitting this!

**Pull request closed without merging**
